markdown: rdiscount
pygments: true
lsi: true
exclude: ['README.markdown', 'README_FOR_COLLABORATORS.markdown', 'Gemfile.lock', 'Gemfile']
production: false
paginate: 10
paginate_file: index.html
baseurl:/three-person-walking
url: http://vincent-li.github.com/three-person-walking
